# Generated by Django 3.0.4 on 2020-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleambiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='arcond',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
