# Generated by Django 3.0.4 on 2020-04-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleambiente', '0002_ambiente_arcond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='arcond',
        ),
    ]
