# Generated by Django 3.0.4 on 2020-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleambiente', '0004_arcondstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcondstate',
            name='onoff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
